# Generated by Django 3.1.5 on 2021-03-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('note', '0001_initial'),
        ('user', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.task'),
        ),
        migrations.AddField(
            model_name='note',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='user.UserGroup'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist',
                                    to='note.note'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistitem',
            unique_together={('position', 'note')},
        ),
    ]
