# Generated by Django 3.1.5 on 2021-03-19 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0003_auto_20210319_1240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('created_by', 'title')},
        ),
    ]
