# Generated by Django 3.1.5 on 2021-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('note', '0004_auto_20210319_1302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('created_by', 'title'), name='unique-in-module'),
        ),
    ]
