# Generated by Django 3.1.5 on 2021-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_note_hashcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='hashcode',
            field=models.CharField(default='0000', max_length=1000, unique=True),
        ),
    ]
