# Generated by Django 3.1.5 on 2021-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_auto_20210520_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='hashcode',
            field=models.CharField(default='0000', max_length=1000, unique=True),
        ),
    ]
