# Generated by Django 3.1.5 on 2021-03-10 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_auto_20210310_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('is_archieved', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Business'), (0, 'Personal')], default=0)),
                ('start_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('business_services', models.ManyToManyField(related_name='tasks', to='service.Service')),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_created',
                                   to=settings.AUTH_USER_MODEL)),
                ('service_providers',
                 models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('tagged_users',
                 models.ManyToManyField(blank=True, related_name='task_tagged', to=settings.AUTH_USER_MODEL)),
                ('user_groups', models.ManyToManyField(blank=True, to='user.UserGroup')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
