# Generated by Django 3.1.5 on 2021-03-14 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasks',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='subtask_provider', to=settings.AUTH_USER_MODEL),
        ),
    ]
