# Generated by Django 3.1.5 on 2021-03-19 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_subtasks_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('created_by', 'title')},
        ),
    ]
