# Generated by Django 3.1.5 on 2021-04-20 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_auto_20210319_1323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('created_by', 'title', 'created_at')},
        ),
    ]
