# Generated by Django 3.1.5 on 2021-05-28 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0012_auto_20210528_0251'),
        ('task', '0008_auto_20210519_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_cat', to='business.businesscategory')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_business', to='business.business')),
                ('feedback_tags', models.ManyToManyField(blank=True, to='task.FeedbackTags')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_provider', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_task', to='task.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
