# Generated by Django 3.1.5 on 2021-05-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_feedback_feedbacktags'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('provider', 'user', 'task'), name='feedback-in-module'),
        ),
    ]
