# Generated by Django 3.1.5 on 2021-06-11 12:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20210528_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
