# Generated by Django 3.1.5 on 2021-05-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20210306_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_cat', to='business.businesscategory')),
            ],
        ),
    ]
