# Generated by Django 3.1.5 on 2021-05-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
