# Generated by Django 3.1.5 on 2021-05-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210514_0805'),
        ('business', '0008_auto_20210514_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usergroup'),
        ),
    ]
