# Generated by Django 3.1.5 on 2021-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_providerdetail'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='providerdetail',
            constraint=models.UniqueConstraint(fields=('provider', 'business'), name='unique-in-detail'),
        ),
    ]
