# Generated by Django 3.1.5 on 2021-05-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20210524_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktags',
            name='category',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='FeedbackTags',
        ),
    ]
