# Generated by Django 3.1.5 on 2021-06-11 12:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20210528_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
