# Generated by Django 3.1.5 on 2021-06-17 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0013_auto_20210611_1224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('name', 'created_by')},
        ),
    ]
