# Generated by Django 3.1.5 on 2021-03-10 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'ordering': ['-last_activity_at'], 'permissions': [('group_admin', 'Admin access in group')]},
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.Group'),
        ),
    ]
