# Generated by Django 3.1.5 on 2021-05-24 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210514_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('experience', models.TextField()),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
