# Generated by Django 3.1.5 on 2021-05-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_providerdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderDetail',
        ),
    ]
