# Generated by Django 3.1.5 on 2021-05-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_providerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='image',
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
