# Generated by Django 3.1.5 on 2021-03-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='archieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0),
        ),
    ]
