# Generated by Django 3.1.5 on 2021-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210310_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hashcode',
            field=models.CharField(default='0000', max_length=1000, unique=True),
        ),
    ]
