# Generated by Django 3.1.5 on 2021-06-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20210617_1130'),
        ('service', '0003_service_hashcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('business', 'name')},
        ),
    ]
